package org.jbpm.examples.exceptions.service;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExceptionService implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ExceptionService() {
    }




}